### ISSUE TITLE
BSD or MIT license?

### ISSUE THREAD

**Issue by highc007** [HarryHarcourt/Ansible-RHEL7-CIS-Benchmarks#17]
While reviewing this item, we noticed an inconsistency between the license referenced in the 'external' descriptor at:

https://github.com/HarryHarcourt/Ansible-RHEL7-CIS-Benchmarks#license
License
BSD.

And what is indicated in the actual code one would download, ~/meta/main.yml indicates:
license: MIT

While both are license types I'm generally permitted to work with, I'll need to know which prevails.
Also, I'll note that both BSD and MIT require 
"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." 
and I'm not finding the notice anywhere in the material I'd download; if I've missed it somewhere, please advise.
  Thanks,
  Chris.

**Comment by HarryHarcourt** [comment]
Hi Chris
I do not know how to answer this.  I took the original code from Antony Courtney for Amazon Linux and ‘ported it’ to RHEL.
We have a few choices:
1) do nothing (have not even looked at this)
2) I talk to someone at my work who I hope would be more familiar with the questions you have and try to resolve it (but my work is not affiliated in any shape or form with this)
3) Tell me what it should be and why, I can review and update
Want people to use this because I have been though such pain over the years.
Also note - if you are a member of the Center for Internet Security you can download and run their assessment tool against your servers for free (thus validating the configuration.
Best
Ben

**Comment by highc007** [comment]
Thanks for the quick reply, Ben...
I'll reference from 3. ... I really can't 'tell' you.  It's up to the copy right owner to decide; and if you copied then ported it with no intent to change the license (and I'm hazy if it would be permissible for you to do so even if you wished to), then we should probably go to Antony and ask.
I think once that is settled, then which ever one 'wins', you should make sure the correct license text is embedded into at least one file in what is included in the download package.
I've found that package, and it looks like the same structure exists (I haven't searched out to see if the license text is embedded anywhere... so we can't just look back to the source to determine the intended license.  I'll go nudge.
  (I don't believe the CIS mechanism is via the Ansible approach, and there's a number of problems we'd like to tackle using Ansible (so we have one mechanism to support, rather than several), so... at least for the moment, I'm tied to looking for Ansible based solutions.)
  thanks,
   Chris.

**Comment by HarryHarcourt** [comment]
Hi Chris
I see you have asked Anthony already, I will look to his response, thanks
Best
Ben

**Comment by HarryHarcourt** [comment]
Hi Chris
How long do we wait?
Best
Ben

**Comment by HarryHarcourt** [comment]
Hi Chris
Can I simply change mine to MIT?
Best
Ben

**Comment by highc007** [comment]
Hi Ben,
  I can't answer 'how long to wait'.  My 'project' is at a very tentative assessment state; it's not 100% clear this bit I'm looking at will be implemented under Ansible, Chef or ???  So...  
  'Can' you?  I'm not an OpenSource License expert.  You have obviously 'borrowed' from the previous project; as such, I believe you are bound by the license terms of it for at least the portions of the materials you didn't originate.  It's clear to me you intended to honor the license of the original project.  But the licensing at the originating end is not clear (and has not been clarified (yet)).  I honestly don't know if you are at liberty to select a license at this point.  -If- the license at the originating end were clear (and it be one of the ones discussed in the other thread), I'd be very confident you could simply stick to those original license terms and be 'good to go'.  If you wanted to change to a different license... again, not an expert.  I only know I need to know what license applies before initiating a project that uses OpenSource.

**Comment by HarryHarcourt** [comment]
Have also notified Anthony on LinkedIn that we are pending.

**Comment by highc007** [comment]
Good idea.
I spoke with someone who is more familiar with opensource; I gather you are 'at liberty' to document in your own license file what the licenses that were documented under Anthony's project (List them all, proper attribution), then indicate what license your contribution is under.  I gather that some licenses don't play well together; but BSD and MIT do... so you 'can' indicate your contributions are then covered under MIT.  *Neither of us are lawyers, we recommend you do your own research and reach your own conclusions.

**Comment by HarryHarcourt** [comment]
Hi Chris
If I don't get a response by tonight, I will simply put a License file in place and reference the source and the challenges with it.
Best
Ben

**Comment by highc007** [comment]
Hey Ben,
  That seems entirely reasonable.  I'll simply watch for the update.  Thanks for your attention.
    Chris.

**Comment by HarryHarcourt** [comment]
Ok - updated, let me know.
Ben

**Comment by highc007** [comment]
Thanks Ben.
As I mentioned before, it's not even a 'sure thing' that Ansible will be chosen as the mechanism, or that OpenSource will be chosen over 'in house' of the role; however, I do believe I have what I need to be able to put this in the running.
If someone more knowledgeable than me about licensing indicates that something more/better/different would improve the stance, I'll share back as appropriate.  I do, though, believe this is a distinct step forward/clarification.  I appreciate the change.

**Comment by HarryHarcourt** [comment]
Hi Chris
I am not selling anything, I struggled in this space (CIS Benchmarks) for many years and am happy to feed my efforts back to the community.  It is a great way to learn.
I will start on RHEL8 soon enough.
Best
Ben

**Comment by highc007** [comment]
Understood, and deeply respect and appreciate your contribution in the OpenSource space.
