### ISSUE TITLE
2.1.6

### ISSUE THREAD

**Issue by ghost** [HarryHarcourt/Ansible-RHEL7-CIS-Benchmarks#20]
This should be about tftp server, but is about rsh instead. No?

**Comment by HarryHarcourt** [comment]
Hi Roman
2.1.9 is about tftp, does the CIS Benchmarks refer to tftp under 2.1.6 in there for RHEL?
Best

**Comment by ghost** [comment]
It seems that way. Here is a doc...

**Comment by HarryHarcourt** [comment]
Hi Roman
Did not find a document from you but did reference the CIS Benchmarks for RHEL7, yes you are correct.  I know where this inconsistency occurred, because this was originally forked from the CIS-Amazon Linux Benchmarks.
What do you want to happen?
Best
Ben

**Comment by ghost** [comment]
Nothing really. :)

Just wanted to let you know.

**Comment by HarryHarcourt** [comment]
Hi Roman
I think this is a history thing between Amazon Linux and RHEL from the CIS Benchmarks, it is not a perfect mapping (I trust like the RHEL / CentOS number mapping).
Unless it is causing people specific issues I am going to leave it as is.
I would note that if people are a subscriber to Center for Internet Security they can / should use the Benchmark Assessor Tool which would validate much of the configuration.
Best
Ben
